// <auto-generated />
using ApiUsers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUsers.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220313225853_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("ApiUsers.Data.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Content = "Este es el post 1 con contenido muy divertido.",
                            Title = "Post 1"
                        },
                        new
                        {
                            id = 2,
                            Content = "Este es el post 2 con contenido muy divertido.",
                            Title = "Post 2"
                        },
                        new
                        {
                            id = 3,
                            Content = "Este es el post 3 con contenido muy divertido.",
                            Title = "Post 3"
                        },
                        new
                        {
                            id = 4,
                            Content = "Este es el post 4 con contenido muy divertido.",
                            Title = "Post 4"
                        },
                        new
                        {
                            id = 5,
                            Content = "Este es el post 5 con contenido muy divertido.",
                            Title = "Post 5"
                        },
                        new
                        {
                            id = 6,
                            Content = "Este es el post 6 con contenido muy divertido.",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
